# -*- coding: utf-8 -*-
"""unit06_folium_seoul_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rGc7cVnRsZQO2L02tty47Uu7B7OFlS43
"""

import pandas as pd

dat = pd.read_csv("seoul_public_toilet.csv" , engine ='python', encoding='EUCKR')
dat

dat.columns

dat_tmp = dat.loc[ :, ['대명칭', 'WSG84Y좌표', 'WSG84X좌표' ]   ]
dat_tmp

import folium

# 중앙 위치 찾기
dat_tmp.columns = ['name', 'latitude', 'longitude']
print( dat_tmp.latitude.mean(), dat_tmp.longitude.mean() )
dat_tmp.head()

m = folium.Map(location = [37.5447, 126.9828], zoom_start=10)
m

### 200개 만 얻기
dat_200 = dat_tmp.iloc[0:200, :]
dat_200

size = dat_200.name.count()
print(size)   # 크기

print(dat_200.columns)

import time

# %%time
now = time.time()

m = folium.Map(location = [37.5447, 126.9828], zoom_start=13)

for i in range(size):
  folium.Marker(location= [ dat_200.loc[i, 'latitude']  , dat_200.loc[i, 'longitude'] ] ,
                tooltip= dat_200.loc[i, 'name']  ,
          ).add_to(m)

work_time = time.time() - now
m.save("seoul_data.html")
print( work_time )
# m

# %%time
now = time.time()

m = folium.Map(location = [37.5447, 126.9828], zoom_start=13)

for i in range(size):
  folium.Marker(location= [ dat_200.loc[i, 'latitude']  , dat_200.loc[i, 'longitude'] ] ,
                tooltip= dat_200.loc[i, 'name']  ,
             icon=folium.DivIcon(html=f"""<div style="font-family: courier new; color: blue">{dat_200.loc[i, 'name']}</div>""")
          ).add_to(m)

work_time = time.time() - now
m.save("seoul_data_c.html")
print( work_time )
# m

